### ISSUE TITLE
Sequence Number is missing in NodeDataReceivedAsync & NodeBirthReceivedAsync

### ISSUE THREAD

**Issue by ankitagojiya** [SeppPenner/SparkplugNet#59]
According to the Sparkplug specification, we must submit a REBIRTH request if we get a message out of order. However, the NodeData which we receive in the host application(using NodeDataReceivedAsync ) just includes metrics not sequence number. 
 
![image](https://github.com/SeppPenner/SparkplugNet/assets/152958503/3a4fa30f-af71-43d4-ad95-719eec192364)

**Comment by SeppPenner** [comment]
Need to check this.

**Comment by ankitagojiya** [comment]
Hello @SeppPenner  
any updated on this .
Need this to implement reorder timeout functionality using this.

**Comment by SeppPenner** [comment]
> Hello @SeppPenner any updated on this . Need this to implement reorder timeout functionality using this.

Sorry, I haven't started with this yet. The plan is to work on this today and tomorrow.

**Comment by SeppPenner** [comment]
Do you want this to be within the list of metrics or do you want to have this as seperate property like I did it in https://github.com/SeppPenner/SparkplugNet/commit/611afa9cdc044419c80abd78bc8b5550ed10e78c?

**Comment by SeppPenner** [comment]
This should be fixed in version > 1.3.5+. Check https://github.com/SeppPenner/SparkplugNet/commit/9cb2deb43492926293c49338667bbd83eb6a286b that implicitely fixed this.

**Comment by ankitagojiya** [comment]
Hello @SeppPenner 
Thanks for the above updates.
I have verified it in the latest release (1.3.8) but i am still not getting Seq Number in NBIRTH or NDATA event. For the clarification i  am referring to Seq number like below image not the bdseq(sessionNumber) metrics.

![image](https://github.com/SeppPenner/SparkplugNet/assets/152958503/4a0a193d-5cbe-4328-8f86-377dae7dc368)

**Comment by SeppPenner** [comment]
> Hello @SeppPenner Thanks for the above updates. I have verified it in the latest release (1.3.8) but i am still not getting Seq Number in NBIRTH or NDATA event. For the clarification i am referring to Seq number like below image not the bdseq(sessionNumber) metrics.
> 
> ![image](https://private-user-images.githubusercontent.com/152958503/335459650-4a0a193d-5cbe-4328-8f86-377dae7dc368.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjczNTgsIm5iZiI6MTcxOTkyNzA1OCwicGF0aCI6Ii8xNTI5NTg1MDMvMzM1NDU5NjUwLTRhMGExOTNkLTVjYmUtNDMyOC04Zjg2LTM3N2RhZTdkYzM2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQxMzMwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjg0ZjRhNjY3NmZmYzIwM2Q4YzE4ODZlZGExMDQyOGMxNTczNjNlZGQ3ZWE1YzQyZDVmNjRjYWQwOTJhMjA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZC13_vSuPr8tP8FJNg4ZvdylhFeVChPch5SmZWMPqQM)

Thanks for the clearification, need to check this.
